# Generated by Django 4.1.1 on 2022-10-03 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('channel_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('parameters', models.TextField(verbose_name='parameters')),
                ('title', models.TextField(default='Content Title', max_length=200, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('Link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MyContentAnalyser.links')),
                ('main_content', models.TextField(verbose_name='Main Content')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentFetchInfo',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MyContentAnalyser.content')),
                ('processed_words', models.TextField(verbose_name='Processed Words')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MappedKeyWords',
            fields=[
                ('content_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MyContentAnalyser.contentfetchinfo')),
                ('mapped_keywords', models.TextField(verbose_name='Mapped keywords')),
                ('mapped_keywords_count', models.IntegerField(null=True, verbose_name='No. of Mapped Words')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnmappedKeywords',
            fields=[
                ('content_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MyContentAnalyser.contentfetchinfo')),
                ('unmapped_keywords', models.TextField(null=True, verbose_name='Unmapped Keywords')),
                ('unmapped_keywords_count', models.IntegerField(null=True, verbose_name='No. of Unmapped Words')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
