# Generated by Django 4.1.1 on 2022-10-03 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyContentAnalyser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='Link',
            new_name='link',
        ),
    ]
